# version: '3.8'

services:
  # 1. Container Frontend (Vue)
  frontend:
    image: node:20-alpine
    container_name: frontend-tbs
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173" # Cổng này aaPanel không dùng, cứ giữ nguyên
    command: sh -c "npm install && npm run dev -- --host"

  # 2. Container Backend (PHP)
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: backend-tbs
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # 3. Container Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: webserver-tbs
    ports:
      - "8888:80" # ĐÃ ĐỔI: Map cổng 80 của Docker ra cổng 8080 của Ubuntu
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # 4. Container Database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-tbs
    ports:
      - "3307:3306" # ĐÃ ĐỔI: Né cổng 3306 của aaPanel
    environment:
      MYSQL_DATABASE: flower_db_server
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: